require('dotenv').config();
const express = require('express');
const https = require('https');
const fs = require('fs');
const path = require('path');
const rateLimit = require('express-rate-limit');
const app = express();

// Rate limiting — protects against bots and attacks
// General API: 100 requests per minute per IP
const apiLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 100,
  message: { error: 'Too many requests — slow down and try again in a minute' }
});
// Voting endpoint: extra strict — 5 votes per minute per IP
const voteLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 5,
  message: { error: 'Too many votes from this IP — please wait a minute' }
});
// Zip code lookup: 20 lookups per minute per IP
const zipLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 20,
  message: { error: 'Too many zip lookups — slow down' }
});

const API_KEY = 'xH3oHkvJab5BzhnVvJ5zXk3bHK5fPqHZ263Asebc';
const BASE_URL = 'https://api.congress.gov/v3';

// Load AI analysis cache from JSON file (generated by Hermes cron)
let analysisCache = {};
const CACHE_FILE = path.join(__dirname, 'bill-analysis.json');
try {
  if (fs.existsSync(CACHE_FILE)) {
    analysisCache = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8'));
    console.log(`Loaded ${Object.keys(analysisCache).length} bill analyses from cache`);
  }
} catch(e) {
  console.error('Could not load analysis cache:', e.message);
}
// Reload cache every 5 minutes
setInterval(() => {
  try {
    if (fs.existsSync(CACHE_FILE)) {
      analysisCache = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8'));
    }
  } catch(e) { /* silent */ }
}, 300000);

app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());

// Helper: fetch from Congress.gov API v3
function congressFetch(urlPath) {
  return new Promise((resolve, reject) => {
    const separator = urlPath.includes('?') ? '&' : '?';
    const url = `${BASE_URL}${urlPath}${separator}format=json`;
    https.get(url, { headers: { 'X-Api-Key': API_KEY } }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode >= 400) {
          console.error(`Congress.gov API error ${res.statusCode} for ${urlPath}: ${data.substring(0, 200)}`);
          resolve(null);
          return;
        }
        try { resolve(JSON.parse(data)); }
        catch(e) {
          console.error(`Parse error for ${urlPath}: ${data.substring(0, 200)}`);
          resolve(null);
        }
      });
    }).on('error', (e) => {
      console.error(`Network error for ${urlPath}:`, e.message);
      resolve(null);
    });
  });
}

// --- States of the USA ---
const STATES = [
  { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' }, { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' }, { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' }, { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' }, { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' }, { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' }, { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' }, { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' }, { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' }
];

// Get total rep count per state (435 House seats)
const STATE_REP_COUNTS = {
  AL:7, AK:1, AZ:9, AR:4, CA:52, CO:8, CT:5, DE:1, FL:28, GA:14,
  HI:2, ID:2, IL:17, IN:9, IA:4, KS:4, KY:6, LA:6, ME:2, MD:8,
  MA:8, MI:13, MN:8, MS:4, MO:8, MT:2, NE:3, NV:4, NH:2, NJ:12,
  NM:3, NY:26, NC:14, ND:1, OH:15, OK:5, OR:6, PA:17, RI:2, SC:7,
  SD:1, TN:9, TX:38, UT:4, VT:1, VA:11, WA:10, WV:2, WI:8, WY:1
};

// --- API Routes ---

// GET /api/states — all 50 states
app.get('/api/states', apiLimiter, (req, res) => {
  res.json(STATES.map(s => ({
    ...s,
    reps: STATE_REP_COUNTS[s.code] || 0
  })));
});

// GET /api/state/:code — House + Senate members for a state (current members only)
app.get('/api/state/:code', apiLimiter, async (req, res) => {
  const code = req.params.code.toUpperCase();
  try {
    const [houseData, senateData] = await Promise.all([
      congressFetch(`/member/${code}?congress=119&chamber=House&limit=60`),
      congressFetch(`/member/${code}?congress=119&chamber=Senate&limit=10`)
    ]);

    function filterCurrent(members, targetChamber) {
      return (members || []).filter(m => {
        const terms = m.terms?.item;
        if (!terms || terms.length === 0) return false;
        const lastTerm = terms[terms.length - 1];
        // Already queried congress=119 so any returned member is current;
        // endYear from congress.gov lags behind for active congresses
        const matchesChamber = lastTerm.chamber && lastTerm.chamber.toLowerCase().includes(targetChamber.toLowerCase());
        return matchesChamber;
      });
    }

    const house = filterCurrent(houseData?.members, 'House');
    const senate = filterCurrent(senateData?.members, 'Senate');

    res.json({ state: code, house, senate });
  } catch (e) {
    console.error(`Error fetching state ${code}:`, e.message);
    res.json({ state: code, house: [], senate: [] });
  }
});

// GET /api/member/:bioguideId — Member details + sponsored legislation (limit 20)
app.get('/api/member/:bioguideId', apiLimiter, async (req, res) => {
  const { bioguideId } = req.params;
  try {
    const [memberData, sponsoredData] = await Promise.all([
      congressFetch(`/member/${bioguideId}`),
      congressFetch(`/member/${bioguideId}/sponsored-legislation?limit=20`)
    ]);
    res.json({
      member: memberData?.member || null,
      sponsored: sponsoredData?.sponsoredLegislation || []
    });
  } catch (e) {
    console.error(`Error fetching member ${bioguideId}:`, e.message);
    res.json({ member: null, sponsored: [] });
  }
});

// GET /api/recent-bills — Recent bills in 119th Congress (limit 50)
app.get('/api/recent-bills', apiLimiter, async (req, res) => {
  try {
    const data = await congressFetch('/bill/119?limit=50&offset=0');
    res.json(data || { bills: [] });
  } catch (e) {
    console.error('Error fetching recent bills:', e.message);
    res.json({ bills: [] });
  }
});

// GET /api/bills/recent?limit=50&offset=0 — Paginated recent bills
app.get('/api/bills/recent', apiLimiter, async (req, res) => {
  const limit = parseInt(req.query.limit) || 50;
  const offset = parseInt(req.query.offset) || 0;
  try {
    const data = await congressFetch(`/bill/119?limit=${limit}&offset=${offset}`);
    res.json(data || { bills: [] });
  } catch (e) {
    console.error('Error fetching recent bills:', e.message);
    res.json({ bills: [] });
  }
});

// GET /api/bills/search?q=keyword — Search bills by keyword (client-side filter on fetched bills)
app.get('/api/bills/search', apiLimiter, async (req, res) => {
  const q = req.query.q;
  if (!q || q.trim() === '') {
    return res.json({ bills: [] });
  }
  const keyword = q.trim().toLowerCase();
  try {
    const data = await congressFetch(`/bill/119?limit=250&offset=0`);
    const bills = (data?.bills || []).filter(b => {
      const title = (b.title || '').toLowerCase();
      const action = (b.latestAction?.text || '').toLowerCase();
      const type = (b.type || '').toLowerCase();
      const number = String(b.number || '');
      return title.includes(keyword) || action.includes(keyword) || 
             `${type} ${number}`.includes(keyword);
    });
    res.json({ bills });
  } catch (e) {
    console.error('Error searching bills:', e.message);
    res.json({ bills: [] });
  }
});

// GET /api/bill/:congress/:type/:number — Bill details + summaries
app.get('/api/bill/:congress/:type/:number', apiLimiter, async (req, res) => {
  const { congress, type, number } = req.params;
  try {
    const [billData, summariesData, actionsData] = await Promise.all([
      congressFetch(`/bill/${congress}/${type}/${number}`),
      congressFetch(`/bill/${congress}/${type}/${number}/summaries`),
      congressFetch(`/bill/${congress}/${type}/${number}/actions?limit=20`)
    ]);
    res.json({
      bill: billData?.bill || null,
      summaries: summariesData?.summaries || [],
      actions: actionsData?.actions || []
    });
  } catch (e) {
    console.error(`Error fetching bill ${congress}/${type}/${number}:`, e.message);
    res.json({ bill: null, summaries: [], actions: [] });
  }
});

// GET /api/bill/:congress/:type/:number/votes — Voting record for a bill
app.get('/api/bill/:congress/:type/:number/votes', apiLimiter, async (req, res) => {
  const { congress, type, number } = req.params;
  try {
    const data = await congressFetch(`/bill/${congress}/${type}/${number}/votes`);
    res.json(data || { votes: [] });
  } catch (e) {
    console.error(`Error fetching votes for ${congress}/${type}/${number}:`, e.message);
    res.json({ votes: [] });
  }
});

// GET /api/national/stats — Aggregate stats for national view
app.get('/api/national/stats', apiLimiter, async (req, res) => {
  try {
    const data = await congressFetch('/bill/119?limit=250&offset=0');
    const bills = data?.bills || [];
    const total = bills.length;
    let byParty = { D: 0, R: 0, I: 0, other: 0 };
    let byStatus = { Introduced: 0, 'Passed House': 0, 'Passed Senate': 0, Enacted: 0, Vetoed: 0, Other: 0 };
    let topics = {};

    bills.forEach(b => {
      // By status
      const status = (b.latestAction?.text || '').toLowerCase();
      if (status.includes('enacted') || status.includes('became law') || status.includes('signed')) byStatus.Enacted++;
      else if (status.includes('veto')) byStatus.Vetoed++;
      else if (b.originChamber === 'House' && (status.includes('passed') || status.includes('agreed'))) byStatus['Passed House']++;
      else if (b.originChamber === 'Senate' && (status.includes('passed') || status.includes('agreed'))) byStatus['Passed Senate']++;
      else if (status.includes('introduced') || !b.latestAction) byStatus.Introduced++;
      else byStatus.Other++;

      // By topic (from subjects)
      if (b.subjects?.subject) {
        (Array.isArray(b.subjects.subject) ? b.subjects.subject : [b.subjects.subject]).forEach(s => {
          const term = (s.term || '').trim();
          if (term) topics[term] = (topics[term] || 0) + 1;
        });
      }
    });

    // Sort topics by count
    const hotTopics = Object.entries(topics)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 15)
      .map(([term, count]) => ({ term, count }));

    res.json({ total, byParty, byStatus, hotTopics });
  } catch (e) {
    console.error('Error fetching national stats:', e.message);
    res.json({ total: 0, byParty: {}, byStatus: {}, hotTopics: [] });
  }
});

// GET /api/analyze-bill — Return cached AI pros/cons for a bill
app.get('/api/analyze-bill', apiLimiter, async (req, res) => {
  const { congress, type, number } = req.query;
  if (!congress || !type || !number) {
    return res.status(400).json({ error: 'Missing bill identifier' });
  }

  const cacheKey = `${congress}/${type}/${number}`.toLowerCase();
  
  // Check in-memory cache
  if (analysisCache[cacheKey]) {
    return res.json({ 
      pros: analysisCache[cacheKey].pros || ['Analysis pending'],
      cons: analysisCache[cacheKey].cons || ['Analysis pending'],
      cached: true 
    });
  }

  // Check file directly (in case memory is stale)
  try {
    if (fs.existsSync(CACHE_FILE)) {
      const fileCache = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8'));
      if (fileCache[cacheKey]) {
        analysisCache[cacheKey] = fileCache[cacheKey]; // sync to memory
        return res.json({ 
          pros: fileCache[cacheKey].pros || ['Analysis pending'],
          cons: fileCache[cacheKey].cons || ['Analysis pending'],
          cached: true 
        });
      }
    }
  } catch(e) { /* silent */ }

  // Not in cache yet — analysis coming soon
  res.json({ 
    pros: ['Analysis will appear after next refresh cycle'],
    cons: ['Analysis will appear after next refresh cycle'],
    cached: false 
  });
});

// --- Voting System ---
const VOTES_FILE = path.join(__dirname, 'votes.json');
let votesCache = {};
try {
  if (fs.existsSync(VOTES_FILE)) {
    votesCache = JSON.parse(fs.readFileSync(VOTES_FILE, 'utf-8'));
    console.log(`Loaded votes for ${Object.keys(votesCache).length} bills`);
  }
} catch(e) {
  console.error('Could not load votes file:', e.message);
}

function saveVotes() {
  try {
    fs.writeFileSync(VOTES_FILE, JSON.stringify(votesCache, null, 2));
  } catch(e) {
    console.error('Could not save votes:', e.message);
  }
}

// POST /api/vote — Submit a vote (approve/disapprove) on a bill
app.post('/api/vote', voteLimiter, (req, res) => {
  const { billId, vote, voter, email } = req.body;
  if (!billId || !vote || !['approve', 'disapprove'].includes(vote)) {
    return res.status(400).json({ error: 'Missing billId or invalid vote (use "approve" or "disapprove")' });
  }
  if (!voter || !voter.trim()) {
    return res.status(400).json({ error: 'Voter name/identifier is required' });
  }
  if (!votesCache[billId]) {
    votesCache[billId] = { approve: 0, disapprove: 0, voters: {} };
  }
  // If this voter already voted on this bill, reject
  if (votesCache[billId].voters[voter.trim()]) {
    return res.status(400).json({ error: `${voter.trim()} has already voted on this bill` });
  }
  votesCache[billId][vote]++;
  votesCache[billId].voters[voter.trim()] = { vote, email: email || '' };
  saveVotes();
  res.json({ billId, ...votesCache[billId], total: votesCache[billId].approve + votesCache[billId].disapprove });
});

// GET /api/votes — Get vote tallies for all bills (for public display)
// NOTE: Only returns counts — voter names/emails are saved to votes.json
// on disk but NOT exposed over the public API (privacy protection)
app.get('/api/votes', apiLimiter, (req, res) => {
  const safe = {};
  Object.entries(votesCache).forEach(([billId, v]) => {
    safe[billId] = { approve: v.approve, disapprove: v.disapprove, total: (v.approve + v.disapprove) };
  });
  res.json(safe);
});

// GET /api/votes/:billId — Get vote tally for a single bill
app.get('/api/votes/:billId', apiLimiter, (req, res) => {
  const { billId } = req.params;
  const v = votesCache[billId] || { approve: 0, disapprove: 0 };
  res.json({ billId, approve: v.approve, disapprove: v.disapprove, total: v.approve + v.disapprove });
});

// GET /api/photo/:bioguideId — Proxy member photos from bioguide.congress.gov
// (direct browser access is blocked by Cloudflare hotlink protection)
app.get('/api/photo/:bioguideId', (req, res) => {
  const id = req.params.bioguideId.replace(/[^A-Za-z0-9]/, '').substring(0, 10);
  if (!id) return res.status(400).end();
  const url = `https://bioguide.congress.gov/bioguide/photo/${id[0].toUpperCase()}/${id}.jpg`;
  https.get(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      'Referer': 'https://bioguide.congress.gov/',
      'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8'
    }
  }, (r) => {
    if (r.statusCode !== 200) return res.status(404).end();
    res.setHeader('Content-Type', 'image/jpeg');
    res.setHeader('Cache-Control', 'public, max-age=86400');
    r.pipe(res);
  }).on('error', () => res.status(404).end());
});

// GET /api/zip/:zip — Look up state by zip code (uses zippopotam.us, free, no key)
app.get('/api/zip/:zip', zipLimiter, (req, res) => {
  const zip = req.params.zip.replace(/\D/g, '').substring(0, 5);
  if (zip.length !== 5) return res.status(400).json({ error: 'Please enter a valid 5-digit zip code' });
  https.get(`https://api.zippopotam.us/us/${zip}`, (r) => {
    let data = '';
    r.on('data', chunk => data += chunk);
    r.on('end', () => {
      try {
        if (r.statusCode === 404) return res.status(404).json({ error: 'Zip code not found — try your state dropdown instead' });
        const d = JSON.parse(data);
        const stateCode = d.places?.[0]?.['state abbreviation'];
        const city = d.places?.[0]?.['place name'] || '';
        if (!stateCode) return res.status(404).json({ error: 'Could not find state for that zip code' });
        res.json({ stateCode, city });
      } catch(e) {
        res.status(500).json({ error: 'Could not look up zip code' });
      }
    });
  }).on('error', () => res.status(500).json({ error: 'Zip lookup failed — please try again' }));
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Capitol Watch running at http://localhost:${PORT}`);
});
